# JVM memory configuration
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft & NeoForge versions
minecraft_version=1.21.4
minecraft_version_range=[1.21.4,1.22)
neoforge_version=21.4.113-beta
neoforge_version_range=[21.4.0,)
loader_version_range=[4,)

# Mod Properties
mod_id=universal_translator
mod_name=Universal Auto Translator
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.universal.translator
mod_authors=HyIsNoob
mod_description=Universal Client-Side Real-Time Auto Translator for Chat & Item Tooltips using Google Translate.
