package com.astervale.translator.listener;

import com.astervale.translator.config.TranslatorConfig;
import com.astervale.translator.engine.TranslationEngine;
import net.minecraft.client.Minecraft;
import net.minecraft.network.chat.Component;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.neoforge.client.event.ClientChatReceivedEvent;

public class ChatEventListener {

    private final TranslationEngine engine;
    private final TranslatorConfig config;

    public ChatEventListener(TranslationEngine engine, TranslatorConfig config) {
        this.engine = engine;
        this.config = config;
    }

    @SubscribeEvent
    public void onPlayerChat(ClientChatReceivedEvent.Player event) {
        handleChat(event.getMessage());
    }

    @SubscribeEvent
    public void onSystemChat(ClientChatReceivedEvent.System event) {
        handleChat(event.getMessage());
    }

    private void handleChat(Component message) {
        if (!config.chatTranslationEnabled || message == null) return;

        String rawText = message.getString();
        if (rawText.isBlank()) return;

        // Skip messages that are already translated or generated by this mod
        if (rawText.contains("[VI]")) return;

        // Only process messages that contain Korean Hangul
        if (!engine.containsKorean(rawText)) return;

        // Asynchronously translate the message
        engine.translateAsync(rawText, translated -> {
            Minecraft client = Minecraft.getInstance();
            if (client == null || client.gui == null || client.gui.getChat() == null) return;

            // Post back to Minecraft main thread
            client.execute(() -> {
                Component translatedComponent = Component.literal(config.chatPrefix + translated);
                client.gui.getChat().addMessage(translatedComponent);
            });
        });
    }
}
